name: duplicate_cleaner
description: Scan and clean duplicate files from phone storage and SD card.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  image: ^4.2.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+1
  mime: ^1.0.6
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
